### ISSUE TITLE
兄弟，有没有使用文档呀

### ISSUE THREAD

**Issue by ghost** [Lawaxi/ShitBoy#1]
比如参数怎么配置

**Comment by Lawaxi** [comment]
mirai2的插件，第一次用的话开启自动生成配置，在群里输入/help可以看到指令，用指令可以自助配置。自己写的话，配置基本是json格式，写也比较清楚。

**Comment by ghost** [comment]
请问微店的cookie怎么拿到呢？

**Comment by Lawaxi** [comment]
看看这个
http://www.lgyzero.top/weidianCookie

**Comment by Lawaxi** [comment]
现在有文档了o(*￣▽￣*)ブ
