### ISSUE TITLE
账号登陆失败

### ISSUE THREAD

**Issue by onlyzqy** [Lawaxi/ShitBoy#11]
口袋无法通过账号密码登录，烦请更新登录方式

**Comment by Lawaxi** [comment]
目前尚未制作短信登陆功能，如果无法使用密码登录，可以在[http://call.lawaxi.net/pocket/](http://call.lawaxi.net/pocket/)网站上用短信登录，然后复制Token并使用Token登录。控制台输入`/shitboy login <token>`或在配置中token项填入即可使用token登录。
