### ISSUE TITLE
监听时间间隔

### ISSUE THREAD

**Issue by onlyzqy** [Lawaxi/ShitBoy#2]
可以缩短监听时间间隔或者变更为可改变吗？0.7.0的监听间隔过长，

**Comment by Lawaxi** [comment]
刚刚更新了0.1.7-test4版本，可以在配置中设置监测时间，见每个条目下的schedule
用法：https://blog.csdn.net/wlm123565/article/details/125557419

**Comment by onlyzqy** [comment]
> 

test4版本，文字消息和图片消息无法发不出来

**Comment by onlyzqy** [comment]
> 刚刚更新了0.1.7-test4版本，可以在配置中设置监测时间，见每个条目下的schedule 用法：https://blog.csdn.net/wlm123565/article/details/125557419
test5版本，翻牌回复，房间回复，语音消息，视频消息，直播都可以正常发出；但是文字和图片消息无法发出。
