### ISSUE TITLE
长时间运行后会报错，消息无法发送

### ISSUE THREAD

**Issue by onlyzqy** [Lawaxi/ShitBoy#3]
W/stderr: Exception in thread "Thread-21743" java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.HashMap.get(Object)" is null
 W/stderr: 	at shitboy-0.1.7-test6.mirai2.jar//net.lawaxi.util.handler.Pocket48Handler.getMessages(Pocket48Handler.java:247)
 W/stderr: 	at shitboy-0.1.7-test6.mirai2.jar//net.lawaxi.util.sender.Pocket48Sender.run(Pocket48Sender.java:47)

**Comment by Lawaxi** [comment]
我试了试这个问题并没有出现，您能说一下您关注的哪位成员的房间吗？
要不然试一试最新的版本，虽然我几乎没改这个地方
