### ISSUE TITLE
是否考虑加入成员上下线、进出房间功能？

### ISSUE THREAD

**Issue by ghost** [Lawaxi/ShitBoy#5]
首先感谢大佬的分享！
不知道后续是否打算加入成员上下线、进出房间等功能呢？如果有，请教一下相关的api，谢谢！

**Comment by Lawaxi** [comment]
你可以用duan602728596/qqtools

**Comment by ghost** [comment]
qqtools现在好像没有这些功能哎，而且我在那边也提了issue，那边说qchat没有上下线的api
不过我也确实见过有yyh的机器人可以报上下线，不知道大佬有没有其它线索
