### ISSUE TITLE
日志报错

### ISSUE THREAD

**Issue by onlyzqy** [Lawaxi/ShitBoy#7]
W/stderr: Exception in thread "Thread-56" java.lang.NullPointerException: Cannot invoke "cn.hutool.json.JSONArray.size()" because "a" is null
W/stderr: 	at shitboy-0.1.9-test3.mirai2.jar//net.lawaxi.util.sender.BilibiliSender.run(BilibiliSender.java:39)

**Comment by Lawaxi** [comment]
b站主站关注还在测试中
产能不足 小伙伴等一等喔~

**Comment by Lawaxi** [comment]
其他功能都可以正常使用

**Comment by Lawaxi** [comment]
0.1.9-test4版本初步完成B站关注功能，小伙伴可以下载使用~ 后续问题请继续留言
